name: Nojunk
version: '1.0'
main: org.example.battleroyale.nojunk.Nojunk
api-version: '1.20'
author: Qfie
commands:
  junk:
    description: Opens the junk filter settings GUI
    usage: /<command>
    permission: nojunk.use
